pipeline:
  deploy:
    image: michalpodeszwa/docker-compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./deploy/docker-deploy.sh
    secrets:
      - pivotaltracker_secret_token
      - bot_slack_token
